// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(ksync_ffiFFI)
import ksync_ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_ksync_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_ksync_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureKsyncFfiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.
// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        // Use Swift's native UTF-8 decoder; `String(bytes:encoding:.utf8)` goes
        // through Foundation's NSString and silently strips a leading U+FEFF BOM.
        // Invalid UTF-8 substitutes U+FFFD instead of trapping (unreachable
        // given Rust's `String` invariant).
        return String(decoding: bytes, as: UTF8.self)
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        // See `lift` above for why we avoid Foundation's NSString-backed decoder here.
        return String(decoding: try readBytes(&buf, count: Int(len)), as: UTF8.self)
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




/**
 * Per-ref attachment progress. Distinct from [`EventObserver`]: a download's
 * percent is not a global `LOCAL_CHANGED`.
 *
 * Same reentrancy contract as [`EventObserver`]: `on_status` is synchronous and
 * must not call back into the engine.
 */
public protocol AttachmentListener: AnyObject, Sendable {
    
    func onStatus(status: FfiAttachmentStatus) 
    
}
/**
 * Per-ref attachment progress. Distinct from [`EventObserver`]: a download's
 * percent is not a global `LOCAL_CHANGED`.
 *
 * Same reentrancy contract as [`EventObserver`]: `on_status` is synchronous and
 * must not call back into the engine.
 */
open class AttachmentListenerImpl: AttachmentListener, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_ksync_ffi_fn_clone_attachmentlistener(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_ksync_ffi_fn_free_attachmentlistener(handle, $0) }
    }

    

    
open func onStatus(status: FfiAttachmentStatus)  {try! rustCall() {
    uniffi_ksync_ffi_fn_method_attachmentlistener_on_status(
            self.uniffiCloneHandle(),
        FfiConverterTypeFfiAttachmentStatus_lower(status),$0
    )
}
}
    

    
}



// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceAttachmentListener {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // Store the vtable directly.
    static let vtable: UniffiVTableCallbackInterfaceAttachmentListener = UniffiVTableCallbackInterfaceAttachmentListener(
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            do {
                try FfiConverterTypeAttachmentListener.handleMap.remove(handle: uniffiHandle)
            } catch {
                print("Uniffi callback interface AttachmentListener: handle missing in uniffiFree")
            }
        },
        uniffiClone: { (uniffiHandle: UInt64) -> UInt64 in
            do {
                return try FfiConverterTypeAttachmentListener.handleMap.clone(handle: uniffiHandle)
            } catch {
                fatalError("Uniffi callback interface AttachmentListener: handle missing in uniffiClone")
            }
        },
        onStatus: { (
            uniffiHandle: UInt64,
            status: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterTypeAttachmentListener.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onStatus(
                     status: try FfiConverterTypeFfiAttachmentStatus_lift(status)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        }
    )

    // Rust stores this pointer for future callback invocations, so it must live
    // for the process lifetime (not just for the init function call).
    //
    // `nonisolated(unsafe)` is needed under Swift 6 strict concurrency.
    // This is safe because the pointee is initialized once during static init
    // and never mutated by either side of the FFI.  Its fields are C function pointers.
    nonisolated(unsafe) static let vtablePtr: UnsafePointer<UniffiVTableCallbackInterfaceAttachmentListener> = {
        let ptr = UnsafeMutablePointer<UniffiVTableCallbackInterfaceAttachmentListener>.allocate(capacity: 1)
        ptr.initialize(to: vtable)
        return UnsafePointer(ptr)
    }()
}

private func uniffiCallbackInitAttachmentListener() {
    uniffi_ksync_ffi_fn_init_callback_vtable_attachmentlistener(UniffiCallbackInterfaceAttachmentListener.vtablePtr)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAttachmentListener: FfiConverter {
    fileprivate static let handleMap = UniffiHandleMap<AttachmentListener>()

    typealias FfiType = UInt64
    typealias SwiftType = AttachmentListener

    public static func lift(_ handle: UInt64) throws -> AttachmentListener {
        if ((handle & 1) == 0) {
            // Rust-generated handle, construct a new class that uses the handle to implement the
            // interface
            return AttachmentListenerImpl(unsafeFromHandle: handle)
        } else {
            // Swift-generated handle, get the object from the handle map
            return try handleMap.remove(handle: handle)
        }
    }

    public static func lower(_ value: AttachmentListener) -> UInt64 {
         if let rustImpl = value as? AttachmentListenerImpl {
             // Rust-implemented object.  Clone the handle and return it
            return rustImpl.uniffiCloneHandle()
         } else {
            // Swift object, generate a new vtable handle and return that.
            return handleMap.insert(obj: value)
         }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AttachmentListener {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: AttachmentListener, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAttachmentListener_lift(_ handle: UInt64) throws -> AttachmentListener {
    return try FfiConverterTypeAttachmentListener.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAttachmentListener_lower(_ value: AttachmentListener) -> UInt64 {
    return FfiConverterTypeAttachmentListener.lower(value)
}






/**
 * Synchronous host observer. `UniFFI` 0.31 + Swift 6 cannot export async foreign
 * traits (`#SendingClosureRisksDataRace`).
 *
 * `on_event` runs on the thread that produced the event, in emission order —
 * events emitted during `apply` / `sync` run while the engine handle's lock is
 * held, so calling back into the engine from the observer deadlocks. Hand the
 * event to another queue or thread (`DispatchQueue`, a `Flow`, an actor) and
 * return.
 */
public protocol EventObserver: AnyObject, Sendable {
    
    func onEvent(event: FfiEngineEvent) 
    
}
/**
 * Synchronous host observer. `UniFFI` 0.31 + Swift 6 cannot export async foreign
 * traits (`#SendingClosureRisksDataRace`).
 *
 * `on_event` runs on the thread that produced the event, in emission order —
 * events emitted during `apply` / `sync` run while the engine handle's lock is
 * held, so calling back into the engine from the observer deadlocks. Hand the
 * event to another queue or thread (`DispatchQueue`, a `Flow`, an actor) and
 * return.
 */
open class EventObserverImpl: EventObserver, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_ksync_ffi_fn_clone_eventobserver(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_ksync_ffi_fn_free_eventobserver(handle, $0) }
    }

    

    
open func onEvent(event: FfiEngineEvent)  {try! rustCall() {
    uniffi_ksync_ffi_fn_method_eventobserver_on_event(
            self.uniffiCloneHandle(),
        FfiConverterTypeFfiEngineEvent_lower(event),$0
    )
}
}
    

    
}



// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceEventObserver {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // Store the vtable directly.
    static let vtable: UniffiVTableCallbackInterfaceEventObserver = UniffiVTableCallbackInterfaceEventObserver(
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            do {
                try FfiConverterTypeEventObserver.handleMap.remove(handle: uniffiHandle)
            } catch {
                print("Uniffi callback interface EventObserver: handle missing in uniffiFree")
            }
        },
        uniffiClone: { (uniffiHandle: UInt64) -> UInt64 in
            do {
                return try FfiConverterTypeEventObserver.handleMap.clone(handle: uniffiHandle)
            } catch {
                fatalError("Uniffi callback interface EventObserver: handle missing in uniffiClone")
            }
        },
        onEvent: { (
            uniffiHandle: UInt64,
            event: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterTypeEventObserver.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onEvent(
                     event: try FfiConverterTypeFfiEngineEvent_lift(event)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        }
    )

    // Rust stores this pointer for future callback invocations, so it must live
    // for the process lifetime (not just for the init function call).
    //
    // `nonisolated(unsafe)` is needed under Swift 6 strict concurrency.
    // This is safe because the pointee is initialized once during static init
    // and never mutated by either side of the FFI.  Its fields are C function pointers.
    nonisolated(unsafe) static let vtablePtr: UnsafePointer<UniffiVTableCallbackInterfaceEventObserver> = {
        let ptr = UnsafeMutablePointer<UniffiVTableCallbackInterfaceEventObserver>.allocate(capacity: 1)
        ptr.initialize(to: vtable)
        return UnsafePointer(ptr)
    }()
}

private func uniffiCallbackInitEventObserver() {
    uniffi_ksync_ffi_fn_init_callback_vtable_eventobserver(UniffiCallbackInterfaceEventObserver.vtablePtr)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEventObserver: FfiConverter {
    fileprivate static let handleMap = UniffiHandleMap<EventObserver>()

    typealias FfiType = UInt64
    typealias SwiftType = EventObserver

    public static func lift(_ handle: UInt64) throws -> EventObserver {
        if ((handle & 1) == 0) {
            // Rust-generated handle, construct a new class that uses the handle to implement the
            // interface
            return EventObserverImpl(unsafeFromHandle: handle)
        } else {
            // Swift-generated handle, get the object from the handle map
            return try handleMap.remove(handle: handle)
        }
    }

    public static func lower(_ value: EventObserver) -> UInt64 {
         if let rustImpl = value as? EventObserverImpl {
             // Rust-implemented object.  Clone the handle and return it
            return rustImpl.uniffiCloneHandle()
         } else {
            // Swift object, generate a new vtable handle and return that.
            return handleMap.insert(obj: value)
         }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EventObserver {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: EventObserver, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEventObserver_lift(_ handle: UInt64) throws -> EventObserver {
    return try FfiConverterTypeEventObserver.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEventObserver_lower(_ value: EventObserver) -> UInt64 {
    return FfiConverterTypeEventObserver.lower(value)
}






/**
 * Instance-scoped engine handle for Swift/Kotlin (`UniFFI` object).
 */
public protocol KsyncEngineProtocol: AnyObject, Sendable {
    
    func apply(mutationJson: String) throws 
    
    func applyWhere(table: String, op: String, filtersJson: String, columnsJson: String, transformsJson: String, preconditionJson: String) throws  -> [String]
    
    /**
     * One JSON-RPC surface matching `ksync-napi` (`apply`, `sync`, `pull_once`,
     * attachment rows, …). Envelope `{ok, value}` / `{ok:false, error}`.
     *
     * `params_json` may carry the embedder's clock (`now` / `now_ms`); it is
     * pinned for this dispatch only, so both engines stamp the same values from
     * the same request and the typed methods keep stamping with the system
     * clock.
     */
    func call(method: String, paramsJson: String) throws  -> String
    
    func checkpoint() throws  -> FfiCheckpoint
    
    /**
     * Create / replace this handle's engine from `EngineConfig` JSON.
     */
    func create(configJson: String) throws 
    
    func dismissRejection(mutationId: String) throws  -> Bool
    
    func fromFile(table: String, column: String, pk: String, sourcePath: String, mediaType: String?) throws  -> FfiFromFileResult
    
    func getStatus(reference: String) throws  -> FfiAttachmentStatus?
    
    func outboxDepth() throws  -> UInt32
    
    func pullOnce() throws 
    
    func pushOnce() throws 
    
    /**
     * Returns query result JSON (array for many, object/null for single/maybeSingle).
     */
    func query(reqJson: String) throws  -> String
    
    func queryTable(table: String, planJson: String) throws  -> String
    
    func rejections(includeDismissed: Bool) throws  -> [FfiRejection]
    
    func reset() throws  -> [String]
    
    func resolveDownload(reference: String) throws  -> String?
    
    func seedCheckpoint(cursor: String) throws 
    
    func setAccessToken(token: String?) throws 
    
    func setBucket(paramsJson: String) throws 
    
    /**
     * Register a host observer. Events are delivered synchronously on the thread
     * that produced them, while `apply` / `sync` still hold this handle's lock:
     * an observer that calls back into the engine deadlocks, so hand the event
     * to another queue or thread instead (see [`EventObserver`]).
     */
    func subscribe(observer: EventObserver) throws  -> UInt64
    
    func sync() throws 
    
    func unsubscribe(subscriptionId: UInt64) throws 
    
    func unwatch(watchId: UInt64) throws 
    
    func vacuum() throws 
    
    /**
     * Watch one attachment reference. This listener alone receives the current
     * status right away — registering never re-fires the reference's other
     * watchers, which only hear real transitions. Every delivery is synchronous
     * on the calling thread, so a listener must not call back into the engine
     * (see [`AttachmentListener`]).
     */
    func watch(reference: String, listener: AttachmentListener) throws  -> UInt64
    
}
/**
 * Instance-scoped engine handle for Swift/Kotlin (`UniFFI` object).
 */
open class KsyncEngine: KsyncEngineProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_ksync_ffi_fn_clone_ksyncengine(self.handle, $0) }
    }
public convenience init() {
    let handle =
        try! rustCall() {
    uniffi_ksync_ffi_fn_constructor_ksyncengine_new($0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_ksync_ffi_fn_free_ksyncengine(handle, $0) }
    }

    

    
open func apply(mutationJson: String)throws   {try rustCallWithError(FfiConverterTypeKsyncFfiError_lift) {
    uniffi_ksync_ffi_fn_method_ksyncengine_apply(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(mutationJson),$0
    )
}
}
    
open func applyWhere(table: String, op: String, filtersJson: String, columnsJson: String, transformsJson: String, preconditionJson: String)throws  -> [String]  {
    return try  FfiConverterSequenceString.lift(try rustCallWithError(FfiConverterTypeKsyncFfiError_lift) {
    uniffi_ksync_ffi_fn_method_ksyncengine_apply_where(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(table),
        FfiConverterString.lower(op),
        FfiConverterString.lower(filtersJson),
        FfiConverterString.lower(columnsJson),
        FfiConverterString.lower(transformsJson),
        FfiConverterString.lower(preconditionJson),$0
    )
})
}
    
    /**
     * One JSON-RPC surface matching `ksync-napi` (`apply`, `sync`, `pull_once`,
     * attachment rows, …). Envelope `{ok, value}` / `{ok:false, error}`.
     *
     * `params_json` may carry the embedder's clock (`now` / `now_ms`); it is
     * pinned for this dispatch only, so both engines stamp the same values from
     * the same request and the typed methods keep stamping with the system
     * clock.
     */
open func call(method: String, paramsJson: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeKsyncFfiError_lift) {
    uniffi_ksync_ffi_fn_method_ksyncengine_call(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(method),
        FfiConverterString.lower(paramsJson),$0
    )
})
}
    
open func checkpoint()throws  -> FfiCheckpoint  {
    return try  FfiConverterTypeFfiCheckpoint_lift(try rustCallWithError(FfiConverterTypeKsyncFfiError_lift) {
    uniffi_ksync_ffi_fn_method_ksyncengine_checkpoint(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Create / replace this handle's engine from `EngineConfig` JSON.
     */
open func create(configJson: String)throws   {try rustCallWithError(FfiConverterTypeKsyncFfiError_lift) {
    uniffi_ksync_ffi_fn_method_ksyncengine_create(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(configJson),$0
    )
}
}
    
open func dismissRejection(mutationId: String)throws  -> Bool  {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeKsyncFfiError_lift) {
    uniffi_ksync_ffi_fn_method_ksyncengine_dismiss_rejection(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(mutationId),$0
    )
})
}
    
open func fromFile(table: String, column: String, pk: String, sourcePath: String, mediaType: String?)throws  -> FfiFromFileResult  {
    return try  FfiConverterTypeFfiFromFileResult_lift(try rustCallWithError(FfiConverterTypeKsyncFfiError_lift) {
    uniffi_ksync_ffi_fn_method_ksyncengine_from_file(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(table),
        FfiConverterString.lower(column),
        FfiConverterString.lower(pk),
        FfiConverterString.lower(sourcePath),
        FfiConverterOptionString.lower(mediaType),$0
    )
})
}
    
open func getStatus(reference: String)throws  -> FfiAttachmentStatus?  {
    return try  FfiConverterOptionTypeFfiAttachmentStatus.lift(try rustCallWithError(FfiConverterTypeKsyncFfiError_lift) {
    uniffi_ksync_ffi_fn_method_ksyncengine_get_status(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(reference),$0
    )
})
}
    
open func outboxDepth()throws  -> UInt32  {
    return try  FfiConverterUInt32.lift(try rustCallWithError(FfiConverterTypeKsyncFfiError_lift) {
    uniffi_ksync_ffi_fn_method_ksyncengine_outbox_depth(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func pullOnce()throws   {try rustCallWithError(FfiConverterTypeKsyncFfiError_lift) {
    uniffi_ksync_ffi_fn_method_ksyncengine_pull_once(
            self.uniffiCloneHandle(),$0
    )
}
}
    
open func pushOnce()throws   {try rustCallWithError(FfiConverterTypeKsyncFfiError_lift) {
    uniffi_ksync_ffi_fn_method_ksyncengine_push_once(
            self.uniffiCloneHandle(),$0
    )
}
}
    
    /**
     * Returns query result JSON (array for many, object/null for single/maybeSingle).
     */
open func query(reqJson: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeKsyncFfiError_lift) {
    uniffi_ksync_ffi_fn_method_ksyncengine_query(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(reqJson),$0
    )
})
}
    
open func queryTable(table: String, planJson: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeKsyncFfiError_lift) {
    uniffi_ksync_ffi_fn_method_ksyncengine_query_table(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(table),
        FfiConverterString.lower(planJson),$0
    )
})
}
    
open func rejections(includeDismissed: Bool)throws  -> [FfiRejection]  {
    return try  FfiConverterSequenceTypeFfiRejection.lift(try rustCallWithError(FfiConverterTypeKsyncFfiError_lift) {
    uniffi_ksync_ffi_fn_method_ksyncengine_rejections(
            self.uniffiCloneHandle(),
        FfiConverterBool.lower(includeDismissed),$0
    )
})
}
    
open func reset()throws  -> [String]  {
    return try  FfiConverterSequenceString.lift(try rustCallWithError(FfiConverterTypeKsyncFfiError_lift) {
    uniffi_ksync_ffi_fn_method_ksyncengine_reset(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func resolveDownload(reference: String)throws  -> String?  {
    return try  FfiConverterOptionString.lift(try rustCallWithError(FfiConverterTypeKsyncFfiError_lift) {
    uniffi_ksync_ffi_fn_method_ksyncengine_resolve_download(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(reference),$0
    )
})
}
    
open func seedCheckpoint(cursor: String)throws   {try rustCallWithError(FfiConverterTypeKsyncFfiError_lift) {
    uniffi_ksync_ffi_fn_method_ksyncengine_seed_checkpoint(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(cursor),$0
    )
}
}
    
open func setAccessToken(token: String?)throws   {try rustCallWithError(FfiConverterTypeKsyncFfiError_lift) {
    uniffi_ksync_ffi_fn_method_ksyncengine_set_access_token(
            self.uniffiCloneHandle(),
        FfiConverterOptionString.lower(token),$0
    )
}
}
    
open func setBucket(paramsJson: String)throws   {try rustCallWithError(FfiConverterTypeKsyncFfiError_lift) {
    uniffi_ksync_ffi_fn_method_ksyncengine_set_bucket(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(paramsJson),$0
    )
}
}
    
    /**
     * Register a host observer. Events are delivered synchronously on the thread
     * that produced them, while `apply` / `sync` still hold this handle's lock:
     * an observer that calls back into the engine deadlocks, so hand the event
     * to another queue or thread instead (see [`EventObserver`]).
     */
open func subscribe(observer: EventObserver)throws  -> UInt64  {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeKsyncFfiError_lift) {
    uniffi_ksync_ffi_fn_method_ksyncengine_subscribe(
            self.uniffiCloneHandle(),
        FfiConverterTypeEventObserver_lower(observer),$0
    )
})
}
    
open func sync()throws   {try rustCallWithError(FfiConverterTypeKsyncFfiError_lift) {
    uniffi_ksync_ffi_fn_method_ksyncengine_sync(
            self.uniffiCloneHandle(),$0
    )
}
}
    
open func unsubscribe(subscriptionId: UInt64)throws   {try rustCallWithError(FfiConverterTypeKsyncFfiError_lift) {
    uniffi_ksync_ffi_fn_method_ksyncengine_unsubscribe(
            self.uniffiCloneHandle(),
        FfiConverterUInt64.lower(subscriptionId),$0
    )
}
}
    
open func unwatch(watchId: UInt64)throws   {try rustCallWithError(FfiConverterTypeKsyncFfiError_lift) {
    uniffi_ksync_ffi_fn_method_ksyncengine_unwatch(
            self.uniffiCloneHandle(),
        FfiConverterUInt64.lower(watchId),$0
    )
}
}
    
open func vacuum()throws   {try rustCallWithError(FfiConverterTypeKsyncFfiError_lift) {
    uniffi_ksync_ffi_fn_method_ksyncengine_vacuum(
            self.uniffiCloneHandle(),$0
    )
}
}
    
    /**
     * Watch one attachment reference. This listener alone receives the current
     * status right away — registering never re-fires the reference's other
     * watchers, which only hear real transitions. Every delivery is synchronous
     * on the calling thread, so a listener must not call back into the engine
     * (see [`AttachmentListener`]).
     */
open func watch(reference: String, listener: AttachmentListener)throws  -> UInt64  {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeKsyncFfiError_lift) {
    uniffi_ksync_ffi_fn_method_ksyncengine_watch(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(reference),
        FfiConverterTypeAttachmentListener_lower(listener),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeKsyncEngine: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = KsyncEngine

    public static func lift(_ handle: UInt64) throws -> KsyncEngine {
        return KsyncEngine(unsafeFromHandle: handle)
    }

    public static func lower(_ value: KsyncEngine) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> KsyncEngine {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: KsyncEngine, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeKsyncEngine_lift(_ handle: UInt64) throws -> KsyncEngine {
    return try FfiConverterTypeKsyncEngine.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeKsyncEngine_lower(_ value: KsyncEngine) -> UInt64 {
    return FfiConverterTypeKsyncEngine.lower(value)
}




public struct FfiAttachmentStatus: Equatable, Hashable {
    public var state: String
    public var progress: Int64
    public var error: String?
    public var localPath: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(state: String, progress: Int64, error: String?, localPath: String?) {
        self.state = state
        self.progress = progress
        self.error = error
        self.localPath = localPath
    }

    

    
}

#if compiler(>=6)
extension FfiAttachmentStatus: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiAttachmentStatus: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiAttachmentStatus {
        return
            try FfiAttachmentStatus(
                state: FfiConverterString.read(from: &buf), 
                progress: FfiConverterInt64.read(from: &buf), 
                error: FfiConverterOptionString.read(from: &buf), 
                localPath: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiAttachmentStatus, into buf: inout [UInt8]) {
        FfiConverterString.write(value.state, into: &buf)
        FfiConverterInt64.write(value.progress, into: &buf)
        FfiConverterOptionString.write(value.error, into: &buf)
        FfiConverterOptionString.write(value.localPath, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiAttachmentStatus_lift(_ buf: RustBuffer) throws -> FfiAttachmentStatus {
    return try FfiConverterTypeFfiAttachmentStatus.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiAttachmentStatus_lower(_ value: FfiAttachmentStatus) -> RustBuffer {
    return FfiConverterTypeFfiAttachmentStatus.lower(value)
}


public struct FfiCheckpoint: Equatable, Hashable {
    public var cursor: String
    public var softBlocked: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(cursor: String, softBlocked: Bool) {
        self.cursor = cursor
        self.softBlocked = softBlocked
    }

    

    
}

#if compiler(>=6)
extension FfiCheckpoint: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiCheckpoint: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiCheckpoint {
        return
            try FfiCheckpoint(
                cursor: FfiConverterString.read(from: &buf), 
                softBlocked: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: FfiCheckpoint, into buf: inout [UInt8]) {
        FfiConverterString.write(value.cursor, into: &buf)
        FfiConverterBool.write(value.softBlocked, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiCheckpoint_lift(_ buf: RustBuffer) throws -> FfiCheckpoint {
    return try FfiConverterTypeFfiCheckpoint.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiCheckpoint_lower(_ value: FfiCheckpoint) -> RustBuffer {
    return FfiConverterTypeFfiCheckpoint.lower(value)
}


public struct FfiFromFileResult: Equatable, Hashable {
    public var reference: String
    public var sha256: String
    public var size: Int64
    public var mediaType: String
    public var localPath: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(reference: String, sha256: String, size: Int64, mediaType: String, localPath: String) {
        self.reference = reference
        self.sha256 = sha256
        self.size = size
        self.mediaType = mediaType
        self.localPath = localPath
    }

    

    
}

#if compiler(>=6)
extension FfiFromFileResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiFromFileResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiFromFileResult {
        return
            try FfiFromFileResult(
                reference: FfiConverterString.read(from: &buf), 
                sha256: FfiConverterString.read(from: &buf), 
                size: FfiConverterInt64.read(from: &buf), 
                mediaType: FfiConverterString.read(from: &buf), 
                localPath: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiFromFileResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.reference, into: &buf)
        FfiConverterString.write(value.sha256, into: &buf)
        FfiConverterInt64.write(value.size, into: &buf)
        FfiConverterString.write(value.mediaType, into: &buf)
        FfiConverterString.write(value.localPath, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiFromFileResult_lift(_ buf: RustBuffer) throws -> FfiFromFileResult {
    return try FfiConverterTypeFfiFromFileResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiFromFileResult_lower(_ value: FfiFromFileResult) -> RustBuffer {
    return FfiConverterTypeFfiFromFileResult.lower(value)
}


public struct FfiRejection: Equatable, Hashable {
    public var mutationId: String
    public var table: String
    public var pk: String
    public var kind: String
    public var reason: String
    public var changedColumns: [String]
    public var serverRowJson: String
    public var at: Int64
    public var dismissed: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(mutationId: String, table: String, pk: String, kind: String, reason: String, changedColumns: [String], serverRowJson: String, at: Int64, dismissed: Bool) {
        self.mutationId = mutationId
        self.table = table
        self.pk = pk
        self.kind = kind
        self.reason = reason
        self.changedColumns = changedColumns
        self.serverRowJson = serverRowJson
        self.at = at
        self.dismissed = dismissed
    }

    

    
}

#if compiler(>=6)
extension FfiRejection: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiRejection: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiRejection {
        return
            try FfiRejection(
                mutationId: FfiConverterString.read(from: &buf), 
                table: FfiConverterString.read(from: &buf), 
                pk: FfiConverterString.read(from: &buf), 
                kind: FfiConverterString.read(from: &buf), 
                reason: FfiConverterString.read(from: &buf), 
                changedColumns: FfiConverterSequenceString.read(from: &buf), 
                serverRowJson: FfiConverterString.read(from: &buf), 
                at: FfiConverterInt64.read(from: &buf), 
                dismissed: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: FfiRejection, into buf: inout [UInt8]) {
        FfiConverterString.write(value.mutationId, into: &buf)
        FfiConverterString.write(value.table, into: &buf)
        FfiConverterString.write(value.pk, into: &buf)
        FfiConverterString.write(value.kind, into: &buf)
        FfiConverterString.write(value.reason, into: &buf)
        FfiConverterSequenceString.write(value.changedColumns, into: &buf)
        FfiConverterString.write(value.serverRowJson, into: &buf)
        FfiConverterInt64.write(value.at, into: &buf)
        FfiConverterBool.write(value.dismissed, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiRejection_lift(_ buf: RustBuffer) throws -> FfiRejection {
    return try FfiConverterTypeFfiRejection.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiRejection_lower(_ value: FfiRejection) -> RustBuffer {
    return FfiConverterTypeFfiRejection.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * FFI copy of [`EngineEvent`]. `loser_value` stays JSON because `UniFFI` has no
 * `serde_json::Value`.
 */

public enum FfiEngineEvent: Equatable, Hashable {
    
    case localChanged
    case mutationRejected(mutationId: String, reason: String
    )
    case queueDepth(depth: UInt32
    )
    case resetRequired
    case checkpointExpired
    case batchAborted(offenderMutationId: String, reason: String
    )
    case deadLetter(mutationId: String, reason: String
    )
    case columnOverwritten(table: String, pk: String, column: String, loserValueJson: String, winnerMutationId: String, conflictMode: String
    )





}

#if compiler(>=6)
extension FfiEngineEvent: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiEngineEvent: FfiConverterRustBuffer {
    typealias SwiftType = FfiEngineEvent

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiEngineEvent {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .localChanged
        
        case 2: return .mutationRejected(mutationId: try FfiConverterString.read(from: &buf), reason: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .queueDepth(depth: try FfiConverterUInt32.read(from: &buf)
        )
        
        case 4: return .resetRequired
        
        case 5: return .checkpointExpired
        
        case 6: return .batchAborted(offenderMutationId: try FfiConverterString.read(from: &buf), reason: try FfiConverterString.read(from: &buf)
        )
        
        case 7: return .deadLetter(mutationId: try FfiConverterString.read(from: &buf), reason: try FfiConverterString.read(from: &buf)
        )
        
        case 8: return .columnOverwritten(table: try FfiConverterString.read(from: &buf), pk: try FfiConverterString.read(from: &buf), column: try FfiConverterString.read(from: &buf), loserValueJson: try FfiConverterString.read(from: &buf), winnerMutationId: try FfiConverterString.read(from: &buf), conflictMode: try FfiConverterString.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiEngineEvent, into buf: inout [UInt8]) {
        switch value {
        
        
        case .localChanged:
            writeInt(&buf, Int32(1))
        
        
        case let .mutationRejected(mutationId,reason):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(mutationId, into: &buf)
            FfiConverterString.write(reason, into: &buf)
            
        
        case let .queueDepth(depth):
            writeInt(&buf, Int32(3))
            FfiConverterUInt32.write(depth, into: &buf)
            
        
        case .resetRequired:
            writeInt(&buf, Int32(4))
        
        
        case .checkpointExpired:
            writeInt(&buf, Int32(5))
        
        
        case let .batchAborted(offenderMutationId,reason):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(offenderMutationId, into: &buf)
            FfiConverterString.write(reason, into: &buf)
            
        
        case let .deadLetter(mutationId,reason):
            writeInt(&buf, Int32(7))
            FfiConverterString.write(mutationId, into: &buf)
            FfiConverterString.write(reason, into: &buf)
            
        
        case let .columnOverwritten(table,pk,column,loserValueJson,winnerMutationId,conflictMode):
            writeInt(&buf, Int32(8))
            FfiConverterString.write(table, into: &buf)
            FfiConverterString.write(pk, into: &buf)
            FfiConverterString.write(column, into: &buf)
            FfiConverterString.write(loserValueJson, into: &buf)
            FfiConverterString.write(winnerMutationId, into: &buf)
            FfiConverterString.write(conflictMode, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiEngineEvent_lift(_ buf: RustBuffer) throws -> FfiEngineEvent {
    return try FfiConverterTypeFfiEngineEvent.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiEngineEvent_lower(_ value: FfiEngineEvent) -> RustBuffer {
    return FfiConverterTypeFfiEngineEvent.lower(value)
}



public enum KsyncFfiError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case Engine(code: String, msg: String
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension KsyncFfiError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeKsyncFfiError: FfiConverterRustBuffer {
    typealias SwiftType = KsyncFfiError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> KsyncFfiError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Engine(
            code: try FfiConverterString.read(from: &buf), 
            msg: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: KsyncFfiError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Engine(code,msg):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(code, into: &buf)
            FfiConverterString.write(msg, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeKsyncFfiError_lift(_ buf: RustBuffer) throws -> KsyncFfiError {
    return try FfiConverterTypeKsyncFfiError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeKsyncFfiError_lower(_ value: KsyncFfiError) -> RustBuffer {
    return FfiConverterTypeKsyncFfiError.lower(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeFfiAttachmentStatus: FfiConverterRustBuffer {
    typealias SwiftType = FfiAttachmentStatus?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeFfiAttachmentStatus.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeFfiAttachmentStatus.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiRejection: FfiConverterRustBuffer {
    typealias SwiftType = [FfiRejection]

    public static func write(_ value: [FfiRejection], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiRejection.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiRejection] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiRejection]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiRejection.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_ksync_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_ksync_ffi_checksum_method_ksyncengine_apply() != 29735) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ksync_ffi_checksum_method_ksyncengine_apply_where() != 60697) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ksync_ffi_checksum_method_ksyncengine_call() != 17021) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ksync_ffi_checksum_method_ksyncengine_checkpoint() != 63998) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ksync_ffi_checksum_method_ksyncengine_create() != 17921) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ksync_ffi_checksum_method_ksyncengine_dismiss_rejection() != 13695) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ksync_ffi_checksum_method_ksyncengine_from_file() != 40065) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ksync_ffi_checksum_method_ksyncengine_get_status() != 47067) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ksync_ffi_checksum_method_ksyncengine_outbox_depth() != 15502) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ksync_ffi_checksum_method_ksyncengine_pull_once() != 52330) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ksync_ffi_checksum_method_ksyncengine_push_once() != 64419) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ksync_ffi_checksum_method_ksyncengine_query() != 29676) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ksync_ffi_checksum_method_ksyncengine_query_table() != 23733) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ksync_ffi_checksum_method_ksyncengine_rejections() != 10798) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ksync_ffi_checksum_method_ksyncengine_reset() != 30619) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ksync_ffi_checksum_method_ksyncengine_resolve_download() != 31053) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ksync_ffi_checksum_method_ksyncengine_seed_checkpoint() != 28750) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ksync_ffi_checksum_method_ksyncengine_set_access_token() != 35894) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ksync_ffi_checksum_method_ksyncengine_set_bucket() != 10403) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ksync_ffi_checksum_method_ksyncengine_subscribe() != 12996) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ksync_ffi_checksum_method_ksyncengine_sync() != 42902) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ksync_ffi_checksum_method_ksyncengine_unsubscribe() != 12319) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ksync_ffi_checksum_method_ksyncengine_unwatch() != 61961) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ksync_ffi_checksum_method_ksyncengine_vacuum() != 33759) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ksync_ffi_checksum_method_ksyncengine_watch() != 31730) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ksync_ffi_checksum_method_attachmentlistener_on_status() != 14611) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ksync_ffi_checksum_method_eventobserver_on_event() != 22727) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ksync_ffi_checksum_constructor_ksyncengine_new() != 31215) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitAttachmentListener()
    uniffiCallbackInitEventObserver()
    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureKsyncFfiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all